export const catchError = {
   	catch: (error) => {
    	console.log(error)
    }
}